read: [CONVENTIONS.md]

## Lint and fix provided files, or dirty files if none provided
lint: true 

## Specify lint commands to run for different languages, eg: "python: flake8 --select=..." (can be used multiple times)
lint-cmd: "python: ./black-flake8-mypy"

## Enable/disable automatic linting after changes (default: True)
auto-lint: true

test-cmd: ./test
auto-test: true

# I think I want this? Try it
restore-chat-history: true

## Enable/disable automatic acceptance of architect changes (default: True)
auto-accept-architect: false
