read: [CONVENTIONS.md]

dark-mode: true

# I want this config in my repo
gitignore: false


######################################################################
## Enable/disable automatic linting after changes (default: True)

auto-lint: true
test-cmd: "./test --no-cover"
auto-test: true

## Lint and fix provided files, or dirty files if none provided
## This means at load time - no thanks!
lint: false

## Specify lint commands to run for different languages, eg: "python: flake8 --select=..." (can be used multiple times)
lint-cmd: "python: ./black-flake8-mypy"

## Unfortunately, can't tidy the template used by alpine.js
## as it relies on "invalid" attributes that i can't stop tidy from removing.
# lint-cmd: "html: tidy --doctype html5 --indent auto --warn-proprietary-attributes no --drop-empty-elements no -m"

######################################################################
## Commit behavior

attribute-co-authored-by: true
attribute-commit-message-author: true
no-dirty-commits: true
# auto-commits: true
auto-commits: false 

######################################################################
## Misc stuff

# I think I want this? Try it
restore-chat-history: true

## Enable/disable automatic acceptance of architect changes (default: True)
# auto-accept-architect: false

## I am really curious how i am burning so much anthropic usage

llm-history-file: .aider.llm.history.md

# This may help??

cache-prompts: true


#### MODEL DEFAULTS

# TODO: is there a way to make an alias for a whole model config, not just a model name??
model: openrouter/openai/gpt-5
architect: true
edit-format: architect
editor-model: openrouter/openai/gpt-5-mini
editor-edit-format: diff
reasoning-effort: medium
weak-model: openrouter/openai/gpt-5-nano

